### ISSUE TITLE
<plug>(molder-reload) echoes "illegal file name"

### ISSUE THREAD

**Issue by habamax** [mattn/vim-molder#5] opened 2020-10-02 08:32 UTC
Is it possible to not show "illegal file name" message?

![image](https://user-images.githubusercontent.com/234774/94903711-d9c96680-04a2-11eb-9b77-edf7e290b592.png)

Almost the same is with `~` mapping -- it shows "Illegal file name" too.

**Comment by mattn** [comment] 2020-10-02 09:28
The `illegal file name` is not caused by mapping. This is limitation of Vim. I can fix this with suppressing message. Will look in later.

**Comment by mattn** [comment] 2020-10-02 10:59
This should be fixed in latest.

**Closed as completed by mattn** 2020-10-02 10:59 UTC

**Comment by habamax** [comment] 2020-10-02 14:47
Is it possible to make it completely silent?

now every time I go through directories I can see "somedir is a directory" message.

**Comment by mattn** [comment] 2020-10-03 15:50
It is a bug of Vim. And fixed just now.

https://github.com/vim/vim/commit/c8fe645c198e2ca55c4e3446efbbdb9b995c63ce
